version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/application
hooks:
  BeforeInstall:
    - location: .github/deployment/scripts/BeforeInstall.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: .github/deployment/scripts/AfterInstall.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: .github/deployment/scripts/ApplicationStart.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: .github/deployment/scripts/ApplicationStop.sh
      timeout: 300
      runas: root
