version: 0.2
phases:
  build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - public/**/*
    - src/**/*
    - package.json
    - app.js
    - appspec.yml
    - scripts/**/*
